package com.peihua8858.roundview.compiler

import com.google.auto.service.AutoService
import com.google.common.collect.ImmutableSet
import com.peihua8858.roundview.annotation.RoundedView
import com.squareup.javapoet.ClassName
import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.TypeSpec
import com.sun.source.util.Trees
import net.ltgt.gradle.incap.IncrementalAnnotationProcessor
import net.ltgt.gradle.incap.IncrementalAnnotationProcessorType
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.text.MessageFormat
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.annotation.processing.AbstractProcessor
import javax.annotation.processing.ProcessingEnvironment
import javax.annotation.processing.Processor
import javax.annotation.processing.RoundEnvironment
import javax.lang.model.SourceVersion
import javax.lang.model.element.AnnotationMirror
import javax.lang.model.element.AnnotationValue
import javax.lang.model.element.Element
import javax.lang.model.element.ElementKind
import javax.lang.model.element.Modifier
import javax.lang.model.element.TypeElement
import javax.lang.model.type.DeclaredType
import javax.lang.model.type.MirroredTypesException
import javax.tools.Diagnostic
import javax.tools.StandardLocation


@SuppressWarnings("unused")
@AutoService(Processor::class)
@IncrementalAnnotationProcessor(IncrementalAnnotationProcessorType.DYNAMIC)
class RoundedProcessor : AbstractProcessor() {
    companion object {
        private const val CLASS_JAVA_DOC =
            "Generated by Rounded-Processor. Do not edit it!\n" +
                    "@author dingpeihua\n" +
                    "@date %s\n" +
                    "@version 1.0\n"

        private const val PACKAGE_NAME = "com.peihua8858.roundview"
        private const val CLASS_PREFIX = "Rounded"
        private const val ATTRS_XML_PATH: String = "roundViewResValues.xml"
        private const val RESOURCES_TAG: String = "<resources>"
        private const val RESOURCES_END_TAG: String = "</resources>"
        private const val ATTRS_XML_TEMPLATE = " <declare-styleable name=\"{0}\">\n" +
                "        <attr name=\"rv_radius\" />\n" +
                "        <attr name=\"rv_left_top_radius\" />\n" +
                "        <attr name=\"rv_left_bottom_radius\" />\n" +
                "        <attr name=\"rv_right_top_radius\" />\n" +
                "        <attr name=\"rv_right_bottom_radius\" />\n" +
                "        <attr name=\"rv_borderWidth\" />\n" +
                "        <attr name=\"rv_borderColor\" />\n" +
                "        <attr name=\"rv_drawBorder\" />\n" +
                "        <attr name=\"rv_drawCircle\" />\n" +
                "    </declare-styleable>"
    }

    private val mBadgeableMethod: IRoundedMethod by lazy {
        RoundedMethodImpl(PACKAGE_NAME, processingEnv)
    }
    private var trees: Trees? = null

    @Synchronized
    override fun init(processingEnvironment: ProcessingEnvironment?) {
        super.init(processingEnvironment)
        try {
            trees = Trees.instance(processingEnv)
        } catch (ignored: IllegalArgumentException) {
            try {
                // Get original ProcessingEnvironment from Gradle-wrapped one or KAPT-wrapped one.
                for (field in processingEnv.javaClass.declaredFields) {
                    if (field.name.equals("processingEnv")) {
                        field.isAccessible = true
                        val javacEnv = field.get(processingEnv) as ProcessingEnvironment
                        trees = Trees.instance(javacEnv)
                        break
                    }
                }
            } catch (ignored2: Throwable) {
            }
        }
    }

    override fun getSupportedSourceVersion(): SourceVersion? {
        return SourceVersion.latestSupported()
    }

    /**
     * 告知 Processor 哪些注解需要处理
     *
     * @return 返回一个 Set 集合，集合内容为自定义注解的包名+类名
     */
    override fun getSupportedAnnotationTypes(): Set<String> {
        val annotationTypes: MutableSet<String> = LinkedHashSet()
        annotationTypes.add(RoundedView::class.java.canonicalName)
        return annotationTypes
    }

    override fun getSupportedOptions(): Set<String>? {
        if (trees != null) {
            return ImmutableSet.builder<String>().add(IncrementalAnnotationProcessorType.ISOLATING.processorOption)
                .build()
        }
        return super.getSupportedOptions()
    }

    /**
     * 所有的注解处理都是从这个方法开始的，当 APT 找到所有需要处理的注解后，会回调这个方法。当没有属于该 Processor 处理的注解被使用时，不会回调该方法
     *
     * @param set              所有的由该 Processor 处理，并待处理的 Annotations「属于该 Processor 处理的注解，但并未被使用，不存在与这个集合里」
     * @param roundEnvironment 表示当前或是之前的运行环境，可以通过该对象查找到注解
     * @return 表示这组 Annotation 是否被这个 Processor 消费，如果消费「返回 true」后续子的 Processor 不会再对这组 Annotation 进行处理
     */
    override fun process(set: Set<TypeElement?>?, roundEnvironment: RoundEnvironment): Boolean {
        val result = roundEnvironment.classes
        if (result.isEmpty()) {
            return true
        }
        printMessage(Diagnostic.Kind.NOTE, "====================== RoundedProcessor process START ======================")
        try {
            generate(result)
        } catch (e: IllegalAccessException) {
            e.printStackTrace()
        } catch (e: IOException) {
            printMessage(Diagnostic.Kind.ERROR, "Exception occurred when generating class file.")
            e.printStackTrace()
        }
        printMessage(Diagnostic.Kind.NOTE, "====================== RoundedProcessor process END ======================")
        return true
    }

    @Throws(IllegalAccessException::class, IOException::class)
    private fun generate(viewClassSet: List<String>) {
        processingEnv?.apply {
            printMessage(Diagnostic.Kind.NOTE, "生成 " + viewClassSet.size + " 个")
            val classNames = mutableListOf<String>()
            val formater = SimpleDateFormat("yyyy/M/dd HH:mm", Locale.US)
            for (clazz in viewClassSet) {
                val lastDotIndex = clazz.lastIndexOf(".")
                val superPackageName = clazz.substring(0, lastDotIndex)
                val superClassName = clazz.substring(lastDotIndex + 1)
                val className = CLASS_PREFIX + superClassName
                classNames.add(className)
                printMessage(Diagnostic.Kind.NOTE, "$clazz ====> $className")
                val date = formater.format(Date())
                val javaDoc = String.format(CLASS_JAVA_DOC, date)
                val typeBuilder = TypeSpec.classBuilder(className)
                    .addJavadoc(javaDoc)
                    .addModifiers(Modifier.PUBLIC)
                    .superclass(ClassName.get(superPackageName, superClassName))
                    .addSuperinterface(ClassName.get(PACKAGE_NAME, "IRoundedView"))
                    .addField(
                        ClassName.get(PACKAGE_NAME, "RoundViewDelegate"),
                        "mRoundViewDelegate",
                        Modifier.PRIVATE
                    )
                generateMethod(typeBuilder, clazz)
                val javaFile = JavaFile.builder(PACKAGE_NAME, typeBuilder.build()).build()
                javaFile.writeTo(filer)
            }
            // 路径例如: /xxx/app/build/generated/source/kapt/debug
            val kaptPath = processingEnv.kaptGenDir
            printMessage(Diagnostic.Kind.NOTE, "kaptGenDir>>>kaptPath:${kaptPath}")
            val projectDir = kaptPath.parent.parent.parent
            val resOutDir = projectDir.resolve("res").resolve("resValues").resolve(kaptPath.fileName).resolve("values")
            val filePath = Files.createDirectories(resOutDir)
            val attrsFile = resOutDir.resolve(ATTRS_XML_PATH)
            printMessage(Diagnostic.Kind.NOTE, "开始生成 attrs.xml, 生成的目录：$filePath")
            generateAttrsXml(classNames).let { content ->
                try {
                    Files.write(attrsFile, content.toString().toByteArray(StandardCharsets.UTF_8))
                    printMessage(Diagnostic.Kind.NOTE, "生成 attrs.xml 结束")
                } catch (e: Exception) {
                    printMessage(Diagnostic.Kind.NOTE, "生成 attrs.xml 错误,生成的内容：$content\n" +
                                e.stackTraceToString()
                    )
                }
            }
        }
    }
    private val symbolsVisitor = HashSet<String>()
    private val RoundEnvironment.classes: List<String>
        get() {
            val classesStrs = processingEnv.options["classes"]
            printMessage("classes>>>classesStrs:${classesStrs}")
            val result = mutableListOf<String>()
            if (!classesStrs.isNullOrEmpty()) {
                val classes = classesStrs.split("|").map { it.trim() }
                    .filter { it.isNotEmpty() }
                    .distinct()
                classes.forEach {
                    if (it.isNotEmpty()) {
                        if (symbolsVisitor.contains(it)) {
                            return@forEach
                        }
                        result.add(it)
                        symbolsVisitor.add(it)
                    }
                }
                printMessage("classes>>>result:${result}")
                return result
            } else {
                val elements: Set<Element>? = getElementsAnnotatedWith(RoundedView::class.java)
                if (elements.isNullOrEmpty()) {
                    return emptyList()
                }
                elements.forEach {
                    checkAnnotationValid(it, RoundedView::class.java)
                    val classElement = it as TypeElement
                    // 获取该注解的值
                    val badgeAnnotation = classElement.getAnnotation(RoundedView::class.java)
                    try {
                        badgeAnnotation.value
                    } catch (e: MirroredTypesException) {
                        val typeMirrors = e.typeMirrors
                        for (typeMirror in typeMirrors) {
                            val classTypeMirror = typeMirror as DeclaredType
                            val classTypeElement = classTypeMirror.asElement() as TypeElement
                            val qualifiedName = classTypeElement.qualifiedName.toString()
                            result.add(qualifiedName)
                        }
                    }
                }
                return result
            }
        }
    private val ProcessingEnvironment.kaptGenDir: Path
        get() {
            val kaptOut = options["kapt.kotlin.generated"]
            if (kaptOut != null) {
                val path = Paths.get(kaptOut)
                // 路径例如: /xxx/app/build/generated/source/kapt/debug
                printMessage(Diagnostic.Kind.NOTE, "kaptGenDir>>>kaptOut:${path}")
                return path
            }
            val foPath = filer.getResource(StandardLocation.SOURCE_OUTPUT, "", "res")
            printMessage(Diagnostic.Kind.NOTE, "kaptGenDir>>>SOURCE_OUTPUT:${foPath.name}")
            return Paths.get(foPath.name).parent
        }

    private fun generateAttrsXml(classNames: List<String>): String {
        val content = StringBuilder()
        content.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
        content.append("\n")
        content.append(RESOURCES_TAG);
        content.append("\n")
        classNames.forEach {
            content.append(MessageFormat.format(ATTRS_XML_TEMPLATE, it))
            content.append("\n")
        }
        content.append(RESOURCES_END_TAG)
        return content.toString()
    }

    private fun generateMethod(typeBuilder: TypeSpec.Builder, clazz: String) {
        mBadgeableMethod.apply {
            val methods = javaClass.declaredMethods
            for (method in methods) {
                val parameters = method.parameters
                if (parameters.size == 2) {
                    method.invoke(this, typeBuilder, clazz)
                } else {
                    method.invoke(this, typeBuilder)
                }
            }
        }

    }

    private fun checkAnnotationValid(annotatedElement: Element, clazz: Class<*>): Boolean {
        if (annotatedElement.kind != ElementKind.CLASS) {
            error(annotatedElement, "%s must be declared on class.", clazz.simpleName)
            return false
        }
        if (annotatedElement.modifiers.contains(Modifier.PRIVATE)) {
            error(
                annotatedElement,
                "%s must can not be private.",
                (annotatedElement as TypeElement).qualifiedName
            )
            return false
        }
        return true
    }

    private fun error(element: Element, message: String, vararg args: Any) {
        var message1: String = message
        if (args.isNotEmpty()) {
            message1 = String.format(message1, *args)
        }
        printMessage(Diagnostic.Kind.ERROR, message1, element)
    }

    fun printMessage(kind: Diagnostic.Kind, msg: CharSequence) {
        processingEnv?.printMessage(kind, msg)
    }

    fun ProcessingEnvironment.printMessage(kind: Diagnostic.Kind, msg: CharSequence) {
        messager?.printMessage(kind, msg)
    }

    fun printMessage(kind: Diagnostic.Kind?, msg: CharSequence?, e: Element?) {
        processingEnv?.printMessage(kind, msg, e)
    }

    fun ProcessingEnvironment.printMessage(kind: Diagnostic.Kind?, msg: CharSequence?, e: Element?) {
        messager?.printMessage(kind, msg, e)
    }

    fun printMessage(kind: Diagnostic.Kind?, msg: CharSequence?, e: Element?, a: AnnotationMirror?) {
        processingEnv?.printMessage(kind, msg, e, a)
    }

    fun ProcessingEnvironment.printMessage(kind: Diagnostic.Kind?, msg: CharSequence?, e: Element?, a: AnnotationMirror?) {
        messager?.printMessage(kind, msg, e, a)
    }

    fun printMessage(
        kind: Diagnostic.Kind?,
        msg: CharSequence?,
        e: Element?,
        a: AnnotationMirror?,
        v: AnnotationValue?,
    ) {
        processingEnv?.printMessage(kind, msg, e, a, v)
    }

    fun ProcessingEnvironment.printMessage(
        kind: Diagnostic.Kind?,
        msg: CharSequence?,
        e: Element?,
        a: AnnotationMirror?,
        v: AnnotationValue?,
    ) {
        messager?.printMessage(kind, msg, e, a, v)
    }
    fun printMessage(msg: CharSequence) {
        processingEnv?.printMessage(msg)
    }

    fun ProcessingEnvironment.printMessage(msg: CharSequence) {
        messager?.printMessage(Diagnostic.Kind.NOTE, msg)
    }
}